In [ ]:
import torch

In [ ]:
z = torch.zeros(5, 3)
print(z)
print(z.dtype)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
torch.float32


In [ ]:
i = torch.ones((5, 3), dtype=torch.int16)
print(i)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)


In [ ]:
torch.manual_seed(1729)
r1 = torch.rand(2, 2)
print('A random tensor:')
print(r1)

r2 = torch.rand(2, 2)
print('\nA different random tensor: ')
print(r2)  # new values

torch.manual_seed(1729)
r3 = torch.rand(2, 2)
print('\nShould match r1: ')
print(r3) # repeats values of r1 because of re-seed

A random tensor:
tensor([[0.3126, 0.3791],
        [0.3087, 0.0736]])

A different random tensor: 
tensor([[0.4216, 0.0691],
        [0.2332, 0.4047]])

Should match r1: 
tensor([[0.3126, 0.3791],
        [0.3087, 0.0736]])


In [8]:
ones = torch.ones(2, 3)
print(ones)

twos = torch.ones(2, 3) * 2  #every element is multipled by 2
print(twos)

threes = ones + twos     #addition allowed because shapes are similar
print(threes)
print(threes.shape)

r1 = torch.rand(2, 3)
r2 = torch.rand(3, 2)
r3 = r1 + r2

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[3., 3., 3.],
        [3., 3., 3.]])
torch.Size([2, 3])


RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1

In [10]:
r = torch.rand(2, 2) - 0.5 * 2. # values between -1 and 1
print('A random matrix, r:')
print(r)

# Common mathematical operations are supported:
print('\nAbsolute value of r: ')
print(torch.abs(r))

# ...as are trigonometric functions:
print('\nInverse sine of r: ')
print(torch.asin(r))

# ...and linear algebra operations like determinant and singular value decomposition
print('\nDeterminant of r: ')
print(torch.det(r))
print('\nSingular value decompostion of r: ')
print(torch.svd(r))

# ...and statistical and agggreggate operations:
print('\nAverage and standard deviation of r: ')
print(torch.std_mean(r))
print('\nMaximum valuue of r: ')
print(torch.max(r))


A random matrix, r:
tensor([[-0.8616, -0.5241],
        [-0.2519, -0.9639]])

Absolute value of r: 
tensor([[0.8616, 0.5241],
        [0.2519, 0.9639]])

Inverse sine of r: 
tensor([[-1.0383, -0.5516],
        [-0.2547, -1.3012]])

Determinant of r: 
tensor(0.6984)

Singular value decompostion of r: 
torch.return_types.svd(
U=tensor([[-0.7131, -0.7011],
        [-0.7011,  0.7131]]),
S=tensor([1.3142, 0.5314]),
V=tensor([[ 0.6019,  0.7986],
        [ 0.7986, -0.6019]]))

Average and standard deviation of r: 
(tensor(0.3254), tensor(-0.6504))

Maximum valuue of r: 
tensor(-0.2519)
